### ISSUE TITLE
Server crashes when creating a new match

### ISSUE THREAD

**Issue by musashidev** [delucis/bgio-firebase#191]
If I add this db to my server the app crashes when creating new matches with   Error: 3 INVALID_ARGUMENT: Cannot convert an array value in an array value.

```
> node -r esm src/server.js

INFO: App serving on 8000...

  Error: 3 INVALID_ARGUMENT: Cannot convert an array value in an array value.
      at Object.callErrorFromStatus (/home/*/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
      at Object.onReceiveStatus (/home/*/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
      at Object.onReceiveStatus (/home/*/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:342:141)
      at Object.onReceiveStatus (/home/*/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:305:181)
      at process.nextTick (/home/*/node_modules/@grpc/grpc-js/build/src/call-stream.js:124:78)
      at process._tickCallback (internal/process/next_tick.js:61:11)
  Caused by: Error
      at WriteBatch.commit (/home/*/node_modules/@google-cloud/firestore/build/src/write-batch.js:420:23)
      at Firestore.createMatch (/home/*/node_modules/bgio-firebase/dist/firestore.js:50:14)
      at CreateMatch (/home/*/node_modules/boardgame.io/dist/cjs/server.js:1971:14)
      at router.post (/home/*/node_modules/boardgame.io/dist/cjs/server.js:2027:31)
      at dispatch (/home/*/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
      at next (/home/*/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
      at /home/*/node_modules/koa-body/index.js:148:14
      at process._tickCallback (internal/process/next_tick.js:68:7)


```

**Comment by delucis** [comment]
@musashidev This is a restriction that Firestore has:

> An array cannot contain another array value as one of its elements ([Source](https://cloud.google.com/firestore/docs/concepts/data-types#data_types))

As far as I’m aware, boardgame.io itself doesn’t store anything as an array of arrays, so I would guess the array in question is in your game state. I don’t think there’s anything this library can do to get around this basic Firestore limitation unfortunately.

**Comment by musashidev** [comment]
You are right, the problem is in the game state.

Thank you for your help and the project!
